definitions:
  auth.ErrorResponse:
    properties:
      error:
        type: string
      meta:
        type: string
    type: object
  auth.LoginResponse:
    properties:
      refresh_token:
        type: string
      token:
        type: string
    type: object
  auth.LoginWithEmailRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  auth.LoginWithPhoneRequest:
    properties:
      password:
        type: string
      phone:
        type: string
    type: object
  auth.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    type: object
  auth.SendEamilOTPRequest:
    properties:
      email:
        type: string
    type: object
  auth.SendOTPResponse:
    properties:
      expires_in_second:
        type: integer
      message:
        type: string
      method:
        $ref: '#/definitions/auth.method'
      success:
        type: boolean
    type: object
  auth.VerifyEmailOTPRequest:
    properties:
      code:
        type: string
      email:
        type: string
    type: object
  auth.VerifyEmailOTPResponse:
    properties:
      message:
        type: string
      success:
        type: boolean
      token:
        type: string
    type: object
  auth.method:
    enum:
    - email
    type: string
    x-enum-varnames:
    - email
info:
  contact:
    name: Eventic Dev Team
    url: https://github.com/DKeshavarz/eventic
  description: A platform to hold and participate in events
  termsOfService: http://swagger.io/terms/
  title: Eventic
  version: 0.3.0
paths:
  /login-email:
    post:
      consumes:
      - application/json
      description: Login a user with Eamil to app and generate a hwt token and a jwt
        refresh token
      parameters:
      - description: Login info
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/auth.LoginWithEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
      summary: login a user with Eamil
      tags:
      - Auth
  /login-phone:
    post:
      consumes:
      - application/json
      description: Login a user with Phone to app and generate a JWT token and a refresh
        token
      parameters:
      - description: Login info
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/auth.LoginWithPhoneRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
      summary: Login a user with Phone
      tags:
      - Auth
  /refresh-token:
    post:
      consumes:
      - application/json
      description: Refresh the JWT token using a valid refresh token
      parameters:
      - description: Refresh token
        in: body
        name: refresh
        required: true
        schema:
          $ref: '#/definitions/auth.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
      summary: Refresh JWT token
      tags:
      - Auth
  /signup-otp-request:
    post:
      consumes:
      - application/json
      description: Send otp by email to a user for login process of a user
      parameters:
      - description: Login info
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/auth.SendEamilOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.SendOTPResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
      summary: Send otp for a user
      tags:
      - Auth
  /signup-otp-verify:
    post:
      consumes:
      - application/json
      description: Validate otp by email to a user for signup process of a user
      parameters:
      - description: Login info
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/auth.VerifyEmailOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.VerifyEmailOTPResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/auth.ErrorResponse'
      summary: Validate otp for a user
      tags:
      - Auth
securityDefinitions:
  BearerAuth:
    description: 'Type `Bearer ` followed by your JWT token. example: "Bearer abcde12345"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
